import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:supercharged/supercharged.dart';
import 'package:tokoonline/shared/shared.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:flutter_spinkit/flutter_spinkit.dart';
import 'package:tokoonline/widget/widget.dart';

part 'generalpage.dart';
part 'signinpage.dart';
part 'signuppage.dart';
part 'address.dart';
part 'successregister.dart';
part 'homepage.dart';
part 'IllustrationPage.dart';
part 'pagefood.dart';
part 'orderhistorypage.dart';
part 'profilepage.dart';
part 'footpage.dart';